### ISSUE TITLE
Removed feeds from feeds_list aren't removing

### ISSUE THREAD

**Issue by Brody-L** [nivit/polybar-module-news#3]
Hello, 

As the title says, the default feeds_list is persistent. I've rebooted thinking the feeds are cached in RAM, yet the feeds I've added aren't showing and the default feeds continue to show. I'm thinking I may not be using your tool correctly, although it seems pretty straightforward.

Any further information I can provide to help with this?

I'm a noob running arch linux, i3, dual polybars. 

Thank you

p.s, really love your tool btw I'm so happy this exists!

**Comment by nivit** [comment]
Hi,

it is a bug, and I fix it in the incoming release. Meanwhile you can  use this command:

`~/.config/polybar/scripts/news/news.sh select`

to select what feeds to show. You can also  bind it to a keyboard shortcut adding the following line

`bindsym Mod4 + Control + Shift + f exec --no-startup-id ~/.config/polybar/scripts/news/news.sh select`

to `~/.config/i3/config`.

Thank you for this problem report.

**Comment by nivit** [comment]
The release [3.0.3](https://github.com/nivit/polybar-module-news/releases/tag/3.0.3) should fix this bug.
